### ISSUE TITLE
Hot Module Reload - Styles Get Removed

### ISSUE THREAD

**Issue by Shepless** [numical/style-ext-html-webpack-plugin#4] opened 2016-06-08 23:15 UTC
*** Disclaimer - I'm very new to webpack! ***

I have an issue where hot module reloading removes the inlined styles from the head tag. The initial build works fine, but if I change any file to trigger a page reload, the styles disappear. Config is below:

```js
const path = require('path');
const webpack = require('webpack');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const StyleExtHtmlWebpackPlugin = require('style-ext-html-webpack-plugin');
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin');
const PATHS = {
    VENDORS: path.resolve('src/vendors.ts'),
    BOOT: path.resolve('src/boot.ts'),
    POLYFILLS: path.resolve('src/polyfills.ts'),
    ASSETS: path.resolve('src/assets/scss'),
    OUTPUT: path.resolve('.build-output')
};

module.exports = {
    entry: {
        'polyfills': PATHS.POLYFILLS,
        'vendor': PATHS.VENDORS,
        'boot': PATHS.BOOT
    },
    output: {
        path: PATHS.OUTPUT,
        filename: '[name]-[hash].js'
    },
    resolve: {
        extensions: ['', '.json', '.js', '.ts', '.scss', '.html']
    },
    module: {
        loaders: [{
            test: /\.ts?$/,
            loaders: ['ts-loader']
        }, {
            test: /\.html?$/,
            loaders: ['raw']
        }, {
            test: /\.scss?$/,
            loaders: ['raw', 'sass']
        }, {
            test: /main.scss$/,
            loaders: [StyleExtHtmlWebpackPlugin.inline(), 'postcss-loader', 'sass']
        }, {
            test: /\.json?$/,
            loaders: ['json']
        }]
    },
    sassLoader: {
        includePaths: [PATHS.ASSETS]
    },
    plugins: [
        new CleanWebpackPlugin(['.build-output'], {
            root: process.cwd()
        }),
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            favicon: 'src/assets/favicon.ico',
            chunksSortMode: 'dependency'
        }),
        new ScriptExtHtmlWebpackPlugin({
            defaultAttribute: 'defer'
        }),
        new StyleExtHtmlWebpackPlugin(),
        new webpack.optimize.CommonsChunkPlugin(['vendor', 'polyfills']),
    ]
};
```

Any ideas? Am I doing something stupid here?

**Comment by numical** [comment] 2016-06-09 13:32
Hi @Shepless  - sorry for the delay in answering, I'm a bit busy at the moment.  Nothing immediately jumps out at me.  Whilst I have a think can you try [switching off](https://github.com/ampedandwired/html-webpack-plugin#configuration) `HtmlWebpackPlugin`'s cache.
My current thought is that `style-ext-html-webbapck-plugin` is not getting called by  `HtmlWebpackPlugin`during a hot reload for some reason.
Could you also try it without `CleanWebpackPlugin` as I am unfamiliar on how that works and somehow(?) this might be a cause...

**Comment by TombolaShepless** [comment] 2016-06-09 13:36
@numical 14 hours? OSS bud - thats an awesome response time!

Im at work currently, but I certainly will try those suggestions when I get home this evening and feedback. Thanks for pointing me in a general direction 👍

**Comment by numical** [comment] 2016-06-09 13:41
I aim to please :-)
This may finally be the time I have to get around to incorporating [debug](https://www.npmjs.com/package/debug) in the plugin...

**Comment by Shepless** [comment] 2016-06-09 18:43
@numical setting `cache: false` seems to do the trick. Thank you very much. Closing the issue.

**Comment by Shepless** [comment] 2016-06-09 23:39
Sorry @numical it appears that neither of the above approaches work. Apologies for jumping the gun!

After running a few "test cases" I found this:

- Changing a file that is bundled using the `StyleExtHtmlPlugin` doesn't break. The new styles are injected into the HTML correctly, however it does not auto refresh - I need to do it manually

- Changing a file that is NOT bundled using `StyleExtHtmlPlugin` does break. The new styles disappear from the HTML, but is does auto refresh

Hopefully that is of some use?

**Comment by numical** [comment] 2016-06-10 08:40
Yeah - switching off the caching was only ever going to be a work-around.
However - I still suspect the issue it is something to do with caching the wrong output from `html-webpack-plugin`.
To be clear - your cases above are with cache switched off?
Also can i see your webpack command line for your hot-reloading?

**Comment by numical** [comment] 2016-06-10 14:10
OK, I'm struggling to reproduce the problem; so some things to try out:
__1. Config__
I took a closer look at your config.  Can you change:
`loaders: [StyleExtHtmlWebpackPlugin.inline(), 'postcss-loader', 'sass']`
for:
`loaders: StyleExtHtmlWebpackPlugin.inline(['postcss-loader', 'sass'])`
It *might* be that simple but for some reason my test setup crashes when I try to replicate your config.
BTW: I'm no expert but I thought the `postcss-loader` requires its own config values, much like your `sassLoader` section.  See [here](https://www.npmjs.com/package/postcss-loader) for more.

__2. Debug Info__
If not that I'm a little stuck as I cannot replicate the hot reload issue.
By best idea is that the cached compilation no longer holds the `compilation[INLINE_CSS]` data that my loader adds. (If you have not looked at the source, disregard this last sentence).
So can you:
1. update the plugin to the latest v1.0.6
2. prefix the following [debug](https://github.com/visionmedia/debug) flag to your webpack run command: `DEBUG=StyleExtHtmlWebpackPlugin:plugin ` (see example at bottom)
3. Look for these lines in the console output:
```console
StyleExtHtmlWebpackPlugin:plugin addInlineCss
StyleExtHtmlWebpackPlugin:plugin minify
StyleExtHtmlWebpackPlugin:plugin combineInlineCss
StyleExtHtmlWebpackPlugin:plugin insertStylesInHead
``` 
You should get these on every compile.
If not, or more specifically if you see this:
```console
StyleExtHtmlWebpackPlugin:plugin addInlineCss
StyleExtHtmlWebpackPlugin:plugin no compilation[INLINE_CSS}
```
then we are getting closer to the problem

__Example__
Compare and contrast these two commands I use (from my `package.json' file) - the second has the debug flag configured:
```javascript
 "scripts": {
    "dev": "webpack-dev-server --devtool --inline source-map --progress --colors --content-base public",
    "dev:debug": "DEBUG=StyleExtHtmlWebpackPlugin:plugin webpack-dev-server --devtool source-map --inline --progress --colors --content-base public",
    ...
```
(Umm - if you're on Windows, check out [debug](https://github.com/visionmedia/debug) for how to do it).

Hope all/some of this helps...

**Comment by Shepless** [comment] 2016-06-10 22:56
@numical Sorry for the late response. I have realised I have omitted a HUGE piece of information here: I'm using Webpack v2 (currently beta.13) - apologies I should have stated this upfront.

I have tried you're suggestions with no luck. For some reason I can't get any debug information out either which makes this even more painful!

The repo in question is [here](https://github.com/Shepless/angular2-boilerplate) - check out the tree-shaking branch as thats where I have been playing around with your suggestions.

Again sorry for not stating the beta :(

**Comment by Shepless** [comment] 2016-06-11 00:20
I've rolled back the HtmlWebpackPlugin all the way back to v2.6.4 and still no joy so I'm now starting to think that the way I have my config setup will have ever worked? Its getting late now though so Im hitting the sack! Sorry I can't be more help!

**Comment by numical** [comment] 2016-06-11 13:44
Ha.  I have been going over the history of this plugin.  I initially tried to have it incorporated as a [PR](https://github.com/ampedandwired/html-webpack-plugin/pull/256) onto `HtmlWebpackPlugin`.
In that conversation I stated:
> I am not keen to add to the Compilation as:
> 1: Conceptually it seems wrong: my understanding of the Compilation's purpose is to produce javascript and javascript-wrapped assets. Attaching CSS which will have nothing to do with any of the Compilation's assets seems to be mixing concerns.
> 2: And more importantly: I am terrified of modifying core Webpack entities as I really do not yet have a grasp of the possible Unforeseen Consequences..

Well, at least I correctly predicted my current pain...
I think the fix will be to go back to my original idea and use a plug-in specific store wrapped around a `WeakMap` keyed on the `Compilation`.  If it works it should not be much code.

**Comment by numical** [comment] 2016-06-13 11:06
OK @Shepless, version 1.1.x published and (I believe), is Webpack 2 compatible.
Can you check on your codebase and, if OK, close the issue?

**Comment by Shepless** [comment] 2016-06-14 21:24
@numical sorry for not getting back sooner. I have updated to v1.1.0 but I'm still seeing the same issue. Sorry to be a pain!

**Comment by numical** [comment] 2016-06-15 13:03
You're right - it is still not working - and I'm not sure why I thought it did.
Sorry for wasting your time.  My change effectively changed nothing.

Cannot use the `pluginData` as it is not available to the loader.  I need something that is available both at the loading stage and the compilation stage - the `compilation` was great until webpack 2...  My next idea is to use the loader to wrap any css with specific tags and then in the plugin search through the chunks for these tags and extract the css.  If the loader is cached this *might* work with hot reloads.  Else I have to work out how [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin)  works.

As to your final question - that is why I state in the [README](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/README.md):
> The inline loader can be the end of a chain of CSS loaders, though note that any prior loader must output pure CSS, not javascript.

Any LESS/SASS/etc processing must be done in loaders _before_ reaching the plugin's loader.
Maybe I should change the word 'can' to 'must'.

**Comment by Shepless** [comment] 2016-06-15 17:22
No worries, I've enjoyed digging into the insides of Webpack and some of its plugins - great for learning/understanding.

If I can be of any help with the new implementation let me know.

**Comment by jantimon** [comment] 2016-06-17 21:16
For your specs the https://github.com/jantimon/webpack-recompilation-simulator might be helpfull - it allows simulating file changes

**Comment by numical** [comment] 2016-06-17 21:40
@jantimon - thanks!  I have actually looked at your simulator (the `before-resolve` event on `NormalModuleFactory` was a real eye-opener), but I have actually gone for something simpler: 
I fire off `compiler.watch` and pass to its callback a sequence of expected results.  Then I literally update the files.  Still a work in progress, but looking good.
I may be seeking advice from you because the new implementation relies on `compilation.assets[...].source()` which could be incredibly slow on big builds.  Let me get it working first then I will ask your opinion...

**Comment by numical** [comment] 2016-06-20 22:02
@Shepless 
> If I can be of any help with the new implementation let me know.

Well, you asked for it... If you have a chance can you `npm i style-ext-html-webpack-plugin@2.0.0-beta.3` and give it a whirl?  Note that `html-webpack-plugin` cacheing must be off.

I have been making a real pig's ear of this (see the number of betas!) and have some rather questionable stuff in there - but if I know it works outside of my testing then I can then concentrate on beautifying things.

**Comment by Shepless** [comment] 2016-06-20 22:22
@numical gave this a try (with `cache: false`) and it didnt find any styles to extract on the initial compilation (and subsequent re-compilations also), debug output is:

```
StyleExtHtmlWebpackPlugin:plugin optimize-chunk-assets +2s
StyleExtHtmlWebpackPlugin:plugin optimize-chunk-assets +6s
StyleExtHtmlWebpackPlugin:plugin html-webpack-plugin-after-html-processing +4s
StyleExtHtmlWebpackPlugin:plugin addInlineCss +0ms
StyleExtHtmlWebpackPlugin:plugin warning: no extracted css +0ms
```

**Comment by numical** [comment] 2016-06-21 10:45
Oh great.   And I get something completely different:
I forked your [repo](https://github.com/Shepless/angular2-boilerplate) and got (lots of) errors of the form:
```console
ERROR in /home/mikee/sandbox/github/angular2-boilerplate/node_modules/@angular/platform-browser-dynamic/index.d.ts
(73,99): error TS2304: Cannot find name 'Promise'.
ERROR in /home/mikee/sandbox/github/angular2-boilerplate/node_modules/@angular/platform-browser-dynamic/index.d.ts
(74,99): error TS2304: Cannot find name 'Promise'.
ERROR in ./src/app/app.ts
(5,13): error TS2304: Cannot find name 'require'.
```
Knowing next to nothing about Typescript or Angular, I assume it is some polyfill issue but have not a clue how to fix it.  
However I noticed you have included the `NoErrorsPlugin` which prevent files being emitted if compilation errors are reported.  I removed that, and, _et voila_, styles coming through, and being recompiled when they are changed (though the browser is still not auto-refreshing despite the `--inline` option).
Can you confirm this behaviour?  I am still uncertain as this explanation does not explain how you got the debug output you report.

**Comment by TombolaShepless** [comment] 2016-06-21 10:52
To fix those errors you'll need to run `typings i` to get the type definitions for the core-js module and node.js.

I'm at work atm so I cannot test until later this evening. Will feedback then

**Comment by numical** [comment] 2016-06-30 10:19
@TombolaShepless - new name?  Did you get a chance to confirm it works when `NoErrorsPlugin` is removed?

**Comment by numical** [comment] 2016-09-14 10:46
Hiya!  I am close this issue because I assume you either consider it fixed or have given up!
Let me know if I have assumed wrong.

**Closed by numical** 2016-09-14 10:46 UTC
